### ISSUE TITLE
JQuery Free Version?

### ISSUE THREAD

**Issue by Snugug** [filamentgroup/Ajax-Include-Pattern#24]
Are there plans for/would you consider plans for a version of this awesome library that doesn't rely upon jQuery or the like, making it much more portable between various JS frameworks (or without one at all!)

**Comment by scottjehl** [comment]
Sure, we're open to looking at that. 

We often use [Shoestring](https://github.com/filamentgroup/shoestring) to keep costs down, but I understand the advantage of removing a DOM dependency altogether. Hmm. Another easy option is to just make a custom Shoestring build with the handful of methods this script needs... 

Anyway, we're open to ideas!
