### ISSUE TITLE
Loading Page Fragments

### ISSUE THREAD

**Issue by machal** [filamentgroup/Ajax-Include-Pattern#27]
I think it might be possible to insert a portion of the target page:

```
<a data-replace="articles.php#related">Link to related articles</a>
```

Or something which is similar to [jQuery `load()` method](http://api.jquery.com/load/#loading-page-fragments).

**Comment by toddparker** [comment]
We were discussing this recently. I'm not so sure that pulling in the full page, then stripping out the chunk of markup you need is the most efficient but I get that jQuery does that.

If we had the ability to specify the path to a fragment to pull in, would that also work?

**Comment by machal** [comment]
Hmm, you are right – considering the page speed, it is not a good idea to download the entire page and then show only chunk of markup. 
Ignore me please. ;)
