### ISSUE TITLE
What about SEO?

### ISSUE THREAD

**Issue by projenix** [filamentgroup/Ajax-Include-Pattern#29]
I was just thinking about the impact on search engine optimisation as the vast majority of the page content would not be crawlable.

I don't think there will be an answer to this question, I guess it's the tradeoff here, so it's just a thought ..

There must be some way I'm thinking to work WITHIN the newly acquired (but very limited I suppose) javascript crawling abilities of the main search engines (it's fair enough to just care about Google though).

Any thoughts?

**Comment by toddparker** [comment]
@projenix - The idea is the AJAX'd content should generally start out as a link to the content so it's crawlable and navigable w/o JS. Like this:

`<a href="articles-latest.html" data-replace="articles/latest/fragment">Latest Articles</a>`

Ideally, your server can be set up so `articles-latest.html` is just the page wrapper (header/footer) and the fragment so there is re-use of code.
