### ISSUE TITLE
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy

### ISSUE THREAD

**Issue by projenix** [filamentgroup/Ajax-Include-Pattern#30]
I am trying to test the library by using code from this demo: http://filamentgroup.github.io/Ajax-Include-Pattern/test/functional/default.html

I am linking to the js from the latest head and getting this error:
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy     Jquery.js:4:0

Also, what about  Matchmedia and Matchmedia event listener? are these really dependencies too? I included them for now but I hope they are not dependencies too.

Thank you in advance,

**Comment by v0ff4k** [comment]
it appears in circuit request like^
```
var $result = $('#results').append($child1).append($child1);

$child1.append($result);
```
